#!/bin/bash
PROJECT=IterativeParallelism
MY_CLASS=ru.ifmo.ctddev.Nemchenko.${PROJECT}.${PROJECT}
PROJECT_PATH=../HW/out/production/HW/
LOG_FILE=log

PACKAGE_TEST=info.kgeorgiy.java.advanced.concurrent.Tester
LEVEL_TEST=list
ARTIFACTS=../java-advanced-2015/artifacts/IterativeParallelismTest.jar
LIBS=../java-advanced-2015/lib/*
java -cp "../java-advanced-2015/java/*:${ARTIFACTS}:${LIBS}:${PROJECT_PATH}" ${PACKAGE_TEST} ${LEVEL_TEST} ${MY_CLASS} $@
#2> ${LOG_FILE}
